### Send POST request with json body
POST https://rocky-sands-15953.herokuapp.com/api/persons
Content-Type: application/json

{
  "name": "Ulla Leppänen",
  "phone": "050-249912435"
}

###

### Get request with a header
GET https://rocky-sands-15953.herokuapp.com/api/persons
Accept: application/json

###

POST https://rocky-sands-15953.herokuapp.com/api/persons
Content-Type: application/json

{
  "phone": "050-249912435"
}

###

POST https://rocky-sands-15953.herokuapp.com/api/persons
Content-Type: application/json

{
  "name": "Ulla Leppänen"
}

###

DELETE https://rocky-sands-15953.herokuapp.com/api/persons/483470
Content-Type: application/json

###