### Send POST request with json body
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Ulla Leppänen",
  "phone": "050-249912435"
}

###

### Get request with a header
GET http://localhost:3001/api/persons
Accept: application/json

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "phone": "050-249912435"
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Ulla Leppänen"
}

###